// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnowuihjxhiytzgjvnbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJub3d1aWhqeGhpeXR6Z2p2bmJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMjE2MTgsImV4cCI6MjA2Njg5NzYxOH0.0MYVFn4yfSIl25shL1CNd4UoaiLjVHeWySGGhISYq2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});